events {}

http {
    server {
        listen 80;

        # Home page
        location / {
            proxy_pass http://localhost:81;
        }

        # Auth API
        location /auth/ {
            proxy_pass http://localhost:3000/;
        }

        # Dashboard page
        location /dashboard/ {
            proxy_pass http://localhost:82/;
        }

        # Contact page
        location /contact/ {
            proxy_pass http://localhost:83/;
        }

        # Content page
        location /content/ {
            proxy_pass http://localhost:84/;
        }

        # OPTIONAL (very important for clean URL)
        location = /dashboard {
            return 301 /dashboard/;
        }

        location = /contact {
            return 301 /contact/;
        }

        location = /content {
            return 301 /content/;
        }
    }
}}
